### ISSUE TITLE
503 proxy error when user server isn't running

### ISSUE THREAD

**Issue by ryanlovett** [data-8/jupyterhub-deploy#12]
From John:

> Here's a report of a "proxy target missing error" from ~10:30am today. I believe the user is tanmayghai
> 
> > Hi, I submitted my Lab 2 yesterday night and jupyter seemed to be working fine for me. However, now when i try to access both Lab1 or Lab2 I run into a 503: Proxy Target Missing error. How do I fix this?

**Comment by ryanlovett** [comment]
@papajohn I was able to start the server from the Admin console. I do see a proxy error for the user when trying to import a lab asset:

```
18:49:42.299 - error: [ConfigProxy] Proxy error:  code=ECONNREFUSED, errno=ECONNREFUSED, syscall=connect
18:49:42.299 - error: [ConfigProxy] 503 GET /user/tanmayghai/tree/data8assets/labs/lab02
```
Should you field another report, can you have the student make sure to first log in and start their server?

@SamLau95 Do you think interact should start a user's server if it is not already running?

**Comment by SamLau95** [comment]
Currently interact tries to do that when the user gets redirected to their
files. That's what's causing the proxy errors?

ᐧ

On Thu, Jan 28, 2016 at 1:02 PM, Ryan Lovett <notifications@github.com>
wrote:

> @papajohn <https://github.com/papajohn> I was able to start the server
> from the Admin console. I do see a proxy error for the user when trying to
> import a lab asset:
>
> 18:49:42.299 - error: [ConfigProxy] Proxy error:  code=ECONNREFUSED, errno=ECONNREFUSED, syscall=connect
> 18:49:42.299 - error: [ConfigProxy] 503 GET /user/tanmayghai/tree/data8assets/labs/lab02
>
> Should you field another report, can you have the student make sure to
> first log in and start their server?
>
> @SamLau95 <https://github.com/SamLau95> Do you think interact should
> start a user's server if it is not already running?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/data-8/jupyterhub-deploy/issues/12#issuecomment-176414975>
> .
>



-- 
Sam Lau
EECS | UC Berkeley | May 2017
(562) 565-4336 | samlau95@berkeley.edu

**Comment by ryanlovett** [comment]
I think the problem is the interact does not try to start the user's server (see your comment in [DS8-Interact #2](https://github.com/data-8/DS8-Interact/issues/2)). It does verify whether the user is logged in and it redirects to a URL that will work if the user's server is running, but if there is no server then there's no container/jupyter process on the compute node and the proxy will complain (proxy target missing). Try accessing an interact URL when your server isn't up.

We can start the user's server for them by POSTing to the [user server api](https://github.com/jupyter/jupyterhub/blob/master/jupyterhub/apihandlers/users.py#L215), catch any error if it is already running, possible wait until the server is running, then do the redirect. What do you think?

**Comment by SamLau95** [comment]
Sure. Would this fix all the 503 errors we're getting? We're getting a ton
at the moment starting from around last Monday (1/25).
ᐧ

On Thu, Jan 28, 2016 at 10:59 PM, Ryan Lovett <notifications@github.com>
wrote:

> I think the problem is the interact does not try to start the user's
> server (see your comment in DS8-Interact #2
> <https://github.com/data-8/DS8-Interact/issues/2>). It does verify
> whether the user is logged in and it redirects to a URL that will work if
> the user's server is running, but if there is no server then there's no
> container/jupyter process on the compute node and the proxy will complain
> (proxy target missing). Try accessing an interact URL when your server
> isn't up.
>
> We can start the user's server for them by POSTing to the user server api
> <https://github.com/jupyter/jupyterhub/blob/master/jupyterhub/apihandlers/users.py#L215>,
> catch any error if it is already running, possible wait until the server is
> running, then do the redirect. What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/data-8/jupyterhub-deploy/issues/12#issuecomment-176606720>
> .
>



-- 
Sam Lau
EECS | UC Berkeley | May 2017
(562) 565-4336 | samlau95@berkeley.edu

**Comment by jandersonlee** [comment]
Last week we were running out of resources since the docker spawner was
counting idle containers as reserving cpus and VM. We think we have that
covered now.

Some of the remaining errors seem to be from trying to follow the interact
links when a user does *not* have an active container. Ryan has an idea for
that.

Jeff

**Comment by ryanlovett** [comment]
Closed via commit to DS8-interact.
