### ISSUE TITLE
ds8 500 lau******fin

### ISSUE THREAD

**Issue by jandersonlee** [data-8/jupyterhub-deploy#27]
API request failed (500): error

`[I 2016-02-27 20:44:31.103 JupyterHub swarmspawner:57] starting container: image:None`
`[I 2016-02-27 20:44:31.180 JupyterHub dockerspawner:333] Found existing container 'jupyter-lau******fin' (id: e97c1ce)`
`[I 2016-02-27 20:44:31.181 JupyterHub dockerspawner:338] Starting container 'jupyter-lau******fin' (id: e97c1ce)`
`[E 2016-02-27 20:44:31.678 JupyterHub user:192] Unhandled error starting lau******fin's server: 'NoneType' object is not subscriptable`
`[E 2016-02-27 20:44:31.769 JupyterHub web:1524] Uncaught exception POST /hub/api/users/lau******in/server (45.30.89.34)`

Getting the 'NoneType' object is not subscriptable again.

**Comment by jandersonlee** [comment]
[https://docs.google.com/document/d/1LlCUw_4ymOs2bXww8hkng9y1yFgPOzea_Dq6fuQIsVU/edit#]

**Comment by ryanlovett** [comment]
Fixed by 647b54e.
