### ISSUE TITLE
configurable-http-proxy cannot reach user servers

### ISSUE THREAD

**Issue by ryanlovett** [data-8/jupyterhub-deploy#6]
As reported by @jandersonlee:

503: Proxy Target Missing
=========================
The upstream service is unavailable

---
configurable-http-proxy

![unnamed](https://cloud.githubusercontent.com/assets/10248125/12527385/c108c9ea-c12e-11e5-8a57-f41df108d291.png)

Happened at 20160122 17:19.

**Comment by jandersonlee** [comment]
still happening for me on ds8 (data8 seems fine). The console says 13 user running and teh compute nodes (ds1.cs.berkeley.edu and ds2.cs.berkeley.edu) are pretty much idle.

**Comment by jandersonlee** [comment]
Get an API request 500 error when I try to start it from the console.

**Comment by ryanlovett** [comment]
The server reported:
TimeoutError: Server at http://ds2.CS.Berkeley.EDU:32830/user/jandersonlee didn't respond in 30 seconds

I've bumped up the timeout period for server startup as well as for keepalive-type timeout. Previous timeouts were 60s/30s, now they're 300s/150s.

**Comment by jandersonlee** [comment]
Still getting the error - it just takes longer. :^P

**Comment by ryanlovett** [comment]
The hub was reporting:

[W 2016-01-23 02:20:35.069 JupyterHub user:215] jandersonlee's server never showed up at http://ds2.CS.Berkeley.EDU:32834/user/jander
sonlee after 150 seconds. Giving up
[E 2016-01-23 02:20:35.163 JupyterHub gen:871] Exception in Future <tornado.concurrent.Future object at 0x7f99a29e2668> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 867, in error_callback
        future.result()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/user.py", line 231, in spawn
        raise e
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/user.py", line 207, in spawn
        yield self.server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/orm.py", line 110, in wait_up
        yield wait_for_http_server(self.url, timeout=timeout)
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/utils.py", line 84, in wait_for_http_server
        **locals()
    TimeoutError: Server at http://ds2.CS.Berkeley.EDU:32834/user/jandersonlee didn't respond in 150 seconds
    
Your single user container was reporting:
Creating user jandersonlee (1000)
useradd: UID 1000 is not unique
sudo: unknown user: jandersonlee
sudo: unable to initialize policy plugin
Creating user jandersonlee (1000)
useradd: UID 1000 is not unique
sudo: unknown user: jandersonlee
sudo: unable to initialize policy plugin
Creating user jandersonlee (1000)
useradd: UID 1000 is not unique
sudo: unknown user: jandersonlee
sudo: unable to initialize policy plugin
...

I deleted your container. Can you try starting your server again?

**Comment by ryanlovett** [comment]
Wasn't able to determine why this happened, but was able to start the server today.
