### ISSUE TITLE
50X errors when starting servers on JupyterHub

### ISSUE THREAD

**Issue by henryem** [data-8/jupyterhub-deploy#9]
Many students are seeing persistent 500 errors when trying to start their servers.  There's an issue open for the connectors that's probably the same: data8/connector-instructors/#18 .  Just now I'm also seeing 504 errors when trying to start their servers from the admin UI, so maybe the nodes are just really unhappy right now.

@ryanlovett, while this gets sorted out, can you give more instructions on how to run your workaround from that thread (issue #18)?  Basically, I just don't know how to log into the nodes.

Here's a list of accounts that I know were affected today (I can't guarantee they'll stay stuck):
lucas.barbosa
lasobrinho
steveshi

**Comment by ryanlovett** [comment]
This was due to lack of resources yesterday. There weren't enough spare nodes. We've reduced the memory reservation for single user servers which enables us to pack more on a node.

I was just able to start the three user's servers.

From an email thread where this was discussed:
> The mem_limit we had set up for the swarmspawner was 3g which meant that, on the azure ~14gb nodes, we can allocate 4 containers per server. In reality the students haven't been utilizing that much in their servers. We just reduced the memory limit to be 2g and stopped many old user containers. This has freed up enough cores and memory for the students, and should give us 7 containers per server. I loaded the chapter 4 notebook via INTERACT and ran all cells and it completed. Last semester students would sometimes hit a jupyter kernel error citing lack of resources which is why we bumped up the limit from 1g to 3g. If students start to report lack of memory errors, we'll need to increase mem_limit again and either increase the number of nodes or use nodes with more memory per core.
> 
> I need to create a dashboard of some sort which gives us more insight into what the hub things the nodes are doing.

**Comment by henryem** [comment]
One student (username talitha.mcadams) is getting 503 errors today.  I get a 404 error when I try to start her server from the admin interface, which I haven't seen before.

**Comment by ryanlovett** [comment]
Regarding the 503, was she trying to use an interact link before having started her server?

**Comment by henryem** [comment]
Ah, yeah, probably.  I saw the other thread where you said that's a problem.  So for now, students starting a lab need to:

1. Go to data8.berkeley.edu, log in, and start their server
2. Go to data8.org and click on the interact link for the lab

Right?  I'm surprised more students don't run into this problem, because almost no one's server is started when they start a lab.

**Comment by ryanlovett** [comment]
Yes, that is the case, unless I've overlooked something in the interact code.

I'll see if we can get interact to spin up the server for the user prior to redirecting to the imported content.

**Comment by ryanlovett** [comment]
DS8-interact will now start up a user's server if it is not already running. (and if there aren't other issues preventing it from running)
